# log的debug模式, 开启后会使用颜色, 只应该在本地打开debug模式
log_debug: true
http_addr: ":8080"

qiniu:
  access_key: "I50Yj4ceahNUfdGxS-7p5KrnWi*********"
  secret_key: "bIdalJ61Q**********CLzZw3-4DC************jW"
  bucket: "zhuzi-test"

qiniu_url:
  access_token: "https://acc.qbox.me/oauth2/token"
